### ISSUE TITLE
CSV format has semicolon instead of comma

### ISSUE THREAD

**Issue by ajawamnet** [5axes/ImportExportProfiles#3]
export creates a CSV file with semicolons and not commas

example:
ection;Extruder;Key;Type;Value
general;0;Date;str;09/04/2021 20:29:55
general;0;Os;str;Windows 10.0.18362
general;0;Cura_Version;str;4.8.0
general;0;Profile;str;P-I10-6N-1h-2w-F30-2HC-B-A-SG25
general;0;Quality;str;Normal
general;0;Extruder_Count;int;1
resolution;1;layer_height;float;0.1
resolution;1;layer_height_0;float;0.2
resolution;1;line_width;float;0.4
resolution;1;wall_line_width;float;0.4
resolution;1;wall_line_width_0;float;0.4
resolution;1;wall_line_width_x;float;0.4
resolution;1;skin_line_width;float;0.4
resolution;1;infill_line_width;float;0.4
resolution;1;skirt_brim_line_width;float;0.4

**Comment by 5axes** [comment]
That's normal . Csv should be export with semicolon as separate. Comma is used in some countries as decimal separator. So use it at parameter separator is not a good idea.
