### ISSUE TITLE
No, in a REAL CSV it is NOT NORMAL  to use a semicolon as a separator

### ISSUE THREAD

**Issue by ajawamnet** [5axes/ImportExportProfiles#4]
I've been using CSV files for databases since 1988.  You stating:

"That's normal . Csv should be export with semicolon as separate. Comma is used in some countries as decimal separator. So use it at parameter separator is not a good idea."

is NOT CORRECT. 

 Wiki article on CSV:

https://en.wikipedia.org/wiki/Comma-separated_values
Where:
"A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values."

An example of YOUR format:
Section;Extruder;Key;Type;Value
general;0;Date;str;09/04/2021 20:29:55
general;0;Os;str;Windows 10.0.18362
general;0;Cura_Version;str;4.8.0
general;0;Profile;str;P-I10-6N-1h-2w-F30-2HC-B-A-SG25
general;0;Quality;str;Normal

IS INCORRECT - it is a "SEMICOLON SEPARATED FORMAT"  

NOW,  see the wiki article on other delimiter  separated formats:
https://en.wikipedia.org/wiki/Delimiter-separated_values

As to what a CSV SHOULD LOOK LIKE, here's an example of one of a FEW THOUSAND  CSV FILES I have from ALTIUM that I've generated over the past 30 years:

Part Type,Designator,Footprint
,,
10UF-1206,"C1, C2, C3, C4",1206
B550C-13-F,D1,SMC
1812L300/24SLER,F1,POLYMSMDC
1812L075/33DR,F2,POLYMSMDC
FB-1206,"FB1, FB2, FB3, FB4",1206
PNX1715721,J1,PNXEMKDS2-508

Note the use of double quotes  ( " ) used as a qualifier for fields that include a comma.  Go ahead, bring THAT file into something like Excel, Access, MySQL, or any other database/spreadsheet program and you'll see it imports correctly.

YOURS DOES NOT!!

**Comment by 5axes** [comment]
A Real  csv yes, but in the same Wikipedia page "The CSV file format is not fully standardized. The basic idea of separating fields with a comma is clear, but the situation gets complicated when field data also contain commas" . And in every French speaking countries that's the case.   BUT YOU ARE FREE to modify the code for yourself.

**Comment by 5axes** [comment]
Works fine for me with Excel

**Comment by ajawamnet** [comment]
You are misinterpreting the WIKI article.  When they state there's no standard it DOES NOT mean that the main delimiter IS NOT a comma.

It IS ALWAYS a comma. 

If you have French people that use commas for decimal place, then you STILL USE COMMAS to DELIMIT the FIELDS but then USE A SECONDARY DELIMITER - suck as double quotes - to ESCAPE the comma delimit. 

https://en.wikipedia.org/wiki/Escape_character
Where:
"In computing and telecommunication, an escape character is a character that invokes an alternative interpretation on the following characters in a character sequence. An escape character is a particular case of metacharacters. Generally, the judgement of whether something is an escape character or not depends on the context. " 

And what you do if you HAVE COMMAS in the data is as I SHOW in the above CORRECT CSV example - here's it is again:
Part Type,Designator,Footprint
,,
10UF-1206,"C1, C2, C3, C4",1206
B550C-13-F,D1,SMC
1812L300/24SLER,F1,POLYMSMDC
1812L075/33DR,F2,POLYMSMDC
FB-1206,"FB1, FB2, FB3, FB4",1206
PNX1715721,J1,PNXEMKDS2-508

Note that the fields - such as "FB1, FB2, FB3, FB4",  that HAVE COMMAS IN THE FIELD use DOUBLE QUOTES to qualify the fields and further delimit/escape the commas WITH IN THE FIELD.

**Comment by ajawamnet** [comment]
You are misinterpreting the WIKI article.  When they state there's no 
standard it DOES NOT mean that the main delimiter IS NOT a comma.

It IS ALWAYS a comma.

If you have French people that use commas for decimal place, then you 
STILL USE COMMAS to DELIMIT the FIELDS but then USE A SECONDARY 
DELIMITER - suck as double quotes - to ESCAPE the comma delimit.

https://en.wikipedia.org/wiki/Escape_character
Where:
"In computing and telecommunication, an escape character is a character 
that invokes an alternative interpretation on the following characters 
in a character sequence. An escape character is a particular case of 
metacharacters. Generally, the judgement of whether something is an 
escape character or not depends on the context. "

And what you do if you HAVE COMMAS in the data is as I SHOW in the above 
CORRECT CSV example - here's it is again:
Part Type,Designator,Footprint
,,
10UF-1206,"C1, C2, C3, C4",1206
B550C-13-F,D1,SMC
1812L300/24SLER,F1,POLYMSMDC
1812L075/33DR,F2,POLYMSMDC
FB-1206,"FB1, FB2, FB3, FB4",1206
PNX1715721,J1,PNXEMKDS2-508

Note that the fields - such as "FB1, FB2, FB3, FB4",  that HAVE COMMAS 
IN THE FIELD use DOUBLE QUOTES to qualify the fields and further 
delimit/escape the commas WITH IN THE FIELD.

-- 
WAM
http://www.ajawamnet.com
http://www.ajawamnet.com/ajawamnet/marketturd.htm
------------

More information on my lab and shop:
http://www.ajawamnet.com
http://www.ajawamnet.com/ajawam3/swarf/swarf.htm
------------------------

“In the information society, nobody thinks. We expected to banish paper, but we actually banished thought.”
~~ Michael Crichton, Jurassic Park

“You never change things by fighting the existing reality.
To change something, build a new model that makes the existing model obsolete.”
~~R. Buckminster Fuller (1895-1983)

"Success is going from failure to failure without a loss of enthusiasm."
~~ Sir Winston Leonard Spencer-Churchill (1874-1965)

"I've failed at so many things so many times I make Abraham Lincoln look like Bill Gates"
~~ Wayne Mitzen (1959-  )

"What makes an expert isn't so much what they know,
It's that they've done similar things so many times wrong
They know what not to do"
~~ Wayne Mitzen (1959-  )

"You just keep pushing. You just keep pushing. I made every mistake that could be made. But I just kept pushing."
~~ Rene Descartes 1596-1650

"I hate the way people just go from ignorance to despair so quickly; it's the lazy man's option"
~~Professor Tim Flannery (1956-  )

"When you do things right, people won't be sure you've done anything at all."
~~ God, in Futurama episode "Godfellas"

"Two things are infinite: the universe and human stupidity;
and I'm not even sure about the universe."
~~ Albert Einstein (1879-1955)

"Some scientists claim that hydrogen, because it is so plentiful, is the basic building block of the universe.
I dispute that. I say there is more stupidity than hydrogen, and that is the basic building block of the universe."
~~ Frank Zappa (1940-1993)

**Comment by ajawamnet** [comment]
OK so here's examples of what's incorrect and what is correct for CSV files - attached are screenshots of Excel...

![WRONG](https://user-images.githubusercontent.com/25396864/114277508-7ee86d00-99f9-11eb-936d-aae35512367b.png)

![CORRECTED](https://user-images.githubusercontent.com/25396864/114277512-827bf400-99f9-11eb-98b2-0dd911a2965b.png)

![correct sample with commas](https://user-images.githubusercontent.com/25396864/114277517-860f7b00-99f9-11eb-9f3a-bc0d0609eba2.png)

**Comment by 5axes** [comment]
Again feel free to modify the code to what you think is the best for you.
