### ISSUE TITLE
[UI BUG] dialogs Z-order

### ISSUE THREAD

**Issue by yet-another-average-joe** [5axes/ImportExportProfiles#5]
Hi,
and thanks for this plugin, one of the most usefull ones !

There's a problem with the dialogs (Save As and Open) : they are displayed as topmost. Only system modal dialogs should be topmost. Save As and Open are application modal dialogs.
This is ennoying on a single monitor configuration : file explorer is overlapped by the ImportExportProfiles dialog if not resized/moved.

OS : Windows 10

Why exploring while saving a profile ? Because ImportExportProfiles does not provide a default name for the csv file ; the lazy user will want to open the folder and copy paste the project or stl file name instead of typing ! I'm a lazy user.

**Comment by 5axes** [comment]
And what are you doing with lazy user Who don't like to search where is the opened windows or even don't  think that a Windows is already Open and  and just hided behind the main Windows, so they  claim that this plugin had freez the application ? Not sure to change anything on that point. 🤔

**Comment by yet-another-average-joe** [comment]
I think there's some misudunrstanding there ! It was just some humour, but not being fluent with english makes it dificult...

Let me explain : I've been coding a LOT for Windows in the '90 (and  was a MSDN subscriber at this time). I'm used to the MS guidelines for UI design. I just found a mistake in regard to the usual behaviour of dialog boxes under Windows. Here, we have application modal dialogs that display as system modal dialogs (but still behave as application modal). No idea how  dialog boxes are defined in a Qt app, but with Win32 API, it is just a couple of flags.

Under Windows, a window should never display between an application main window and it's modal dialog.

Where did I write that ImportExportProfiles was freezing Cura ?

 I was just reporting a glitch.

**Comment by 5axes** [comment]
J avais bien compris , c etait juste pour signifier que ce comportement était voulu, A prioris (enfin dans les limites de mes connaissances)  on a pas dans le plugin l'infos sur la fenêtre parent . Donc si on ouvre en étant en mode normal , elle risque de passer derrière la fenêtre principale et certains utilisateurs reproche que le plugin bloque Cura, donc pour éviter ça c est un parti pris de mettre la fenêtre de sélection en mode dialogue. Entre pest et choléra j'ai pris cette solution  en attendant peut-être un jour de trouver le vaccin

**Comment by yet-another-average-joe** [comment]
"certains utilisateurs reproche que le plugin bloque Cura" : c'est curieux, puisque c'est normalement le comportement attendu d'un dialogue openfile ou save ou save as : dialogue "application modal". Les autres dialogues de fichiers (par exemple pour exporter un profil ou une matière) ont le comportement habituel...

Maintenant, si l'API des plugins ne permet pas de définir le dialogue comme enfant de la fenêtre principale, il n'y a en effet pas d'autre moyen ! Le problème est donc dans Cura. (du coup, je clos le sujet)

Je viens de voir que "Material costs" a le même comportement.

J'ai mis un petit moment à comprendre parce que je suis sur 4 écrans, avec des fenêtres partout. Mais bon sang où est elle ??? En survolant l'icône dans la barre, et en cliquant sur celle que je cherchais, il ne se passait rien.

Un autre comportement induit : quand le dialogue de fichiers est ouvert, on ne peut plus réduire Cura en cliquant son icône dans la barre de tâches. Ce qui rend encore plus difficile la recherche de la fenêtre qui s'est glissée au milieu.

**Comment by 5axes** [comment]
Les autres export sont dans Cura et pas un Plugin mais encore une fois ça ne veut pas dire que ce n'est pas possible  simplement je ne trouve pas l'infos. Si quelqu'un a un exemple , une piste ou la solution je suis preneur

**Comment by yet-another-average-joe** [comment]
Peut-être un hack ?
Voir le nom de fenêtre, qui contient le nom du fichier courant...
Mais je ne connais pas Qt (à mon grand désespoir, comme pour Python que j'aime pas du tout, mais qui est indispensable de nos jours).

Copie d'écran de ce que donne Spy++ : on peut énumérer les fenêtres de 1er niveau, récupérer leur nom, puis leur handle, et de là faire une fenêtre fille. Je l'ai fait il y a longtemps pour coder une appli compagnon d'un truc sans API. Mais c'était du Win32. Il y a 20 ans.

Si on peut énumérer les fenêtres depuis Qt comme on peut le faire en Win32, on peut matcher son nom avec celui de la fenêtre principale Cura, et récupérer son handle. En Win32 tout du moins. Pas super propre...

![Spy](https://user-images.githubusercontent.com/43514870/122804822-a34da900-d2c8-11eb-9b51-c4d1932a9769.JPG)
